# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl: "morehongming" # the subpath of your site, e.g. /blog
url: "https://hongmingj.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
# Build settings
title: "morehongming"
subtitle: "Career Development"
description: "Career Development"
keywords:blog, zhang0peter
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 3  #主页展示的github仓库数量

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档 

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于


markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 5
paginate_path: "/page/:num"


# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages


# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed
theme: jekyll-theme-cayman